In [1]:
!pip install pyarrow==2 awswrangler

Requirement already satisfied: pyarrow==2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.0.0)
Requirement already satisfied: awswrangler in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.12.1)
Requirement already satisfied: numpy>=1.14 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyarrow==2) (1.19.5)
Requirement already satisfied: openpyxl<3.1.0,>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (3.0.6)
Requirement already satisfied: progressbar2<4.0.0,>=3.53.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (3.55.0)
Requirement already satisfied: boto3<2.0.0,>=1.16.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.20.4)
Requirement already satisfied: requests-aws4auth<2.0.0,>=1.1.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.1.1)
Requirement already satisfied: jsonpath-ng<2.0.0,>=1.5.3 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.5.3)
Requirement already satisfied: xlwt<2.0.0,>=1.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.3.0)
Requirement already satisfied: redshift-connector<2.1.0,>=2.0.887 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.900)
Requirement already satisfied: pandas<1.2.0,>=1.1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.1.5)
Requirement already satisfied: botocore<2.0.0,>=1.19.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.23.4)
Requirement already satisfied: pg8000<1.22.0,>=1.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.21.3)
Requirement already satisfied: xlrd<3.0.0,>=2.0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.1)
Requirement already satisfied: pymysql<1.1.0,>=0.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.0.2)
Requirement already satisfied: opensearch-py<2.0.0,>=1.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.0.0)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.0.0,>=1.16.8->awswrangler) (0.5.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.0.0,>=1.16.8->awswrangler) (0.10.0)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.0.0,>=1.19.8->awswrangler) (1.26.7)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.0.0,>=1.19.8->awswrangler) (2.8.2)
Requirement already satisfied: ply in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from jsonpath-ng<2.0.0,>=1.5.3->awswrangler) (3.11)
Requirement already satisfied: decorator in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from jsonpath-ng<2.0.0,>=1.5.3->awswrangler) (4.4.2)
Requirement already satisfied: six in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from jsonpath-ng<2.0.0,>=1.5.3->awswrangler) (1.16.0)
Requirement already satisfied: et-xmlfile in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.0.1)
Requirement already satisfied: jdcal in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.4.1)
Requirement already satisfied: certifi in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from opensearch-py<2.0.0,>=1.0.0->awswrangler) (2021.10.8)
Requirement already satisfied: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas<1.2.0,>=1.1.0->awswrangler) (2021.3)
Requirement already satisfied: scramp>=1.4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pg8000<1.22.0,>=1.16.0->awswrangler) (1.4.1)
Requirement already satisfied: python-utils>=2.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from progressbar2<4.0.0,>=3.53.3->awswrangler) (2.5.6)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.887->awswrangler) (4.9.3)
Requirement already satisfied: lxml>=4.6.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.887->awswrangler) (4.6.3)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.887->awswrangler) (21.2)
Requirement already satisfied: requests<2.26.1,>=2.23.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.887->awswrangler) (2.26.0)
Requirement already satisfied: soupsieve>1.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from beautifulsoup4<5.0.0,>=4.7.0->redshift-connector<2.1.0,>=2.0.887->awswrangler) (2.0.1)
Requirement already satisfied: idna<4,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.26.1,>=2.23.0->redshift-connector<2.1.0,>=2.0.887->awswrangler) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.26.1,>=2.23.0->redshift-connector<2.1.0,>=2.0.887->awswrangler) (2.0.7)
Requirement already satisfied: asn1crypto>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scramp>=1.4.1->pg8000<1.22.0,>=1.16.0->awswrangler) (1.4.0)
Requirement already satisfied: pyparsing<3,>=2.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from packaging->redshift-connector<2.1.0,>=2.0.887->awswrangler) (2.4.7)
WARNING: You are using pip version 21.2.4; however, version 21.3.1 is available.
You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.

In [2]:
import awswrangler as wr
import pandas as pd
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import numpy as np

In [3]:
end_date = date.today().strftime("%Y-%m-%d")
one_year = date.today() - relativedelta(months=+12)
start_date = one_year.strftime("%Y-%m-%d")

In [4]:
start_date

'2020-11-24'

In [5]:
end_date

'2021-11-24'

In [6]:
sql_th = f"""
SELECT  pv.warehouse, 'week1' as week_id, pv_f1w as lookbook_pv
from
(select
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f1w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 0 AND date_diff('day',dp.date_released ,pv.sent_at) <= 6
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1
) pv
Union all
SELECT  pv.warehouse, 'week2' as week_id, pv_f2w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f2w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 7 AND date_diff('day',dp.date_released ,pv.sent_at) <= 13
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week3' as week_id, pv_f3w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f3w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 14 AND date_diff('day',dp.date_released ,pv.sent_at) <= 20
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week4' as week_id, pv_f4w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f4w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 21 AND date_diff('day',dp.date_released ,pv.sent_at) <= 27
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week5' as week_id, pv_f5w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f5w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 28 AND date_diff('day',dp.date_released ,pv.sent_at) <= 34
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week6' as week_id, pv_f6w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f6w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 35 AND date_diff('day',dp.date_released ,pv.sent_at) <= 41
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week7' as week_id, pv_f7w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f7w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 42 AND date_diff('day',dp.date_released ,pv.sent_at) <= 48
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT pv.warehouse, 'week8' as week_id, pv_f8w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f8w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 49 AND date_diff('day',dp.date_released ,pv.sent_at) <= 55
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week9' as week_id, pv_f9w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f9w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 56 AND date_diff('day',dp.date_released ,pv.sent_at) <= 62
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week10' as week_id, pv_f10w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f10w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 63 AND date_diff('day',dp.date_released ,pv.sent_at) <= 69
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week11' as week_id, pv_f11w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f11w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 70 AND date_diff('day',dp.date_released ,pv.sent_at) <= 76
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week12' as week_id, pv_f12w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f12w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 77 AND date_diff('day',dp.date_released ,pv.sent_at) <= 83
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week13' as week_id, pv_f13w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f13w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 84 AND date_diff('day',dp.date_released ,pv.sent_at) <= 90
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week14' as week_id, pv_f14w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f14w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 91 AND date_diff('day',dp.date_released ,pv.sent_at) <= 97
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week15' as week_id, pv_f15w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f15w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 98 AND date_diff('day',dp.date_released ,pv.sent_at) <= 104
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week16' as week_id, pv_f16w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f16w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 105 AND date_diff('day',dp.date_released ,pv.sent_at) <= 111
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week17' as week_id, pv_f17w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f17w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 112 AND date_diff('day',dp.date_released ,pv.sent_at) <= 118
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
"""

In [7]:
# Retrieving the data from Amazon Athena
df_th_web = wr.athena.read_sql_query(sql_th, database="web_production")

In [8]:
# Retrieving the data from Amazon Athena
df_th_ios = wr.athena.read_sql_query(sql_th, database="ios_pomelo_fashion_production")

In [9]:
df_th_and = wr.athena.read_sql_query(
    sql_th, database="android_pomelo_fashion_production"
)

In [10]:
df_th_web.rename(columns={"lookbook_pv": "lookbook_pv_web"}, inplace=True)

In [11]:
df_th_ios.rename(columns={"lookbook_pv": "lookbook_pv_ios"}, inplace=True)

In [12]:
df_th_and.rename(columns={"lookbook_pv": "lookbook_pv_and"}, inplace=True)

In [13]:
df_th_list = [df_th_web, df_th_ios, df_th_and]

In [14]:
from functools import reduce

In [15]:
df_th = reduce(
    lambda left, right: pd.merge(left, right, on=["warehouse", "week_id"]), df_th_list
)

In [16]:
df_th  # here

   warehouse week_id  lookbook_pv_web  lookbook_pv_ios  lookbook_pv_and
0         TH  week13              125            14199             3741
1         TH  week15              110            13488             3576
2         TH   week1             6090           272805            84195
3         TH  week17               87            11001             2278
4         TH  week16               80            10138             1901
5         TH  week10              394            15935             4582
6         TH   week8              633            23459             6147
7         TH   week7              603            33377             9873
8         TH   week5              810            59422            20421
9         TH   week3             1881            82787            26921
10        TH  week11              337            16034             4038
11        TH  week12              253            18271             4012
12        TH   week2             1973           164506            53370
13        TH  week14              110            16190             5425
14        TH   week4             1626            79168            26155
15        TH   week9              454            20015             4837
16        TH   week6              530            40201            13702

In [17]:
df_th["lookbook_pv"] = (
    df_th["lookbook_pv_web"] + df_th["lookbook_pv_ios"] + df_th["lookbook_pv_and"]
)

In [18]:
df_th = df_th.sort_values("week_id")
df_th

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
2,TH,week1,6090,272805,84195,363090
5,TH,week10,394,15935,4582,20911
10,TH,week11,337,16034,4038,20409
11,TH,week12,253,18271,4012,22536
0,TH,week13,125,14199,3741,18065
13,TH,week14,110,16190,5425,21725
1,TH,week15,110,13488,3576,17174
4,TH,week16,80,10138,1901,12119
3,TH,week17,87,11001,2278,13366
12,TH,week2,1973,164506,53370,219849
9,TH,week3,1881,82787,26921,111589
14,TH,week4,1626,79168,26155,106949
8,TH,week5,810,59422,20421,80653
16,TH,week6,530,40201,13702,54433
7,TH,week7,603,33377,9873,43853
6,TH,week8,633,23459,6147,30239
15,TH,week9,454,20015,4837,25306

# MY

In [19]:
sql_my = f"""
SELECT  pv.warehouse, 'week1' as week_id, pv_f1w as lookbook_pv
from
(select
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f1w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 0 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 6
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1
) pv
Union all
SELECT  pv.warehouse, 'week2' as week_id, pv_f2w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f2w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 7 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 13
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week3' as week_id, pv_f3w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f3w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 14 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 20
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week4' as week_id, pv_f4w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f4w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 21 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 27
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week5' as week_id, pv_f5w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f5w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 28 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 34
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week6' as week_id, pv_f6w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f6w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 35 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 41
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week7' as week_id, pv_f7w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f7w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 42 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 48
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT pv.warehouse, 'week8' as week_id, pv_f8w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f8w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 49 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 55
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week9' as week_id, pv_f9w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f9w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 56 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 62
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week10' as week_id, pv_f10w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f10w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 63 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 69
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week11' as week_id, pv_f11w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f11w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 70 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 76
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week12' as week_id, pv_f12w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f12w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 77 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 83
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week13' as week_id, pv_f13w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f13w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 84 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 90
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week14' as week_id, pv_f14w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f14w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 91 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 97
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week15' as week_id, pv_f15w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f15w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 98 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 104
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week16' as week_id, pv_f16w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f16w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 105 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 111
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week17' as week_id, pv_f17w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f17w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 112 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 118
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv

"""

In [20]:
df_my_web = wr.athena.read_sql_query(sql_my, database="web_production")

In [21]:
df_my_ios = wr.athena.read_sql_query(sql_my, database="ios_pomelo_fashion_production")

In [22]:
df_my_and = wr.athena.read_sql_query(
    sql_my, database="android_pomelo_fashion_production"
)

In [23]:
df_my_web.rename(columns={"lookbook_pv": "lookbook_pv_web"}, inplace=True)

In [24]:
df_my_ios.rename(columns={"lookbook_pv": "lookbook_pv_ios"}, inplace=True)

In [25]:
df_my_and.rename(columns={"lookbook_pv": "lookbook_pv_and"}, inplace=True)

In [26]:
df_my_list = [df_my_web, df_my_ios, df_my_and]

In [27]:
df_my = reduce(
    lambda left, right: pd.merge(left, right, on=["warehouse", "week_id"]), df_my_list
)

In [28]:
df_my

   warehouse week_id  lookbook_pv_web  lookbook_pv_ios  lookbook_pv_and
0         MY   week3              574            15306             7836
1         MY   week8              154             2332             1084
2         MY  week17               25              713              224
3         MY  week13               48             1049              353
4         MY  week14                6              720              212
5         MY  week10              141             3270             1081
6         MY  week16               18              914              328
7         MY   week2              776            26439            13561
8         MY  week11               88             1614              384
9         MY   week1             2801            51603            27352
10        MY   week5              215             5272             3150
11        MY  week12               12             1082              234
12        MY  week15               30             1116              598
13        MY   week4              329            11352             5706
14        MY   week9              131             1741             1074
15        MY   week7              168             4348             2538
16        MY   week6              148             4994             2781

In [29]:
df_my["lookbook_pv"] = (
    df_my["lookbook_pv_web"] + df_my["lookbook_pv_ios"] + df_my["lookbook_pv_and"]
)

In [30]:
df_my = df_my.sort_values("week_id")
df_my

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
9,MY,week1,2801,51603,27352,81756
5,MY,week10,141,3270,1081,4492
8,MY,week11,88,1614,384,2086
11,MY,week12,12,1082,234,1328
3,MY,week13,48,1049,353,1450
4,MY,week14,6,720,212,938
12,MY,week15,30,1116,598,1744
6,MY,week16,18,914,328,1260
2,MY,week17,25,713,224,962
7,MY,week2,776,26439,13561,40776
0,MY,week3,574,15306,7836,23716
13,MY,week4,329,11352,5706,17387
10,MY,week5,215,5272,3150,8637
16,MY,week6,148,4994,2781,7923
15,MY,week7,168,4348,2538,7054
1,MY,week8,154,2332,1084,3570
14,MY,week9,131,1741,1074,2946

# ID

In [31]:
sql_id = f"""
SELECT  pv.warehouse, 'week1' as week_id, pv_f1w as lookbook_pv
from
(select
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f1w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 0 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 6
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1
) pv
Union all
SELECT  pv.warehouse, 'week2' as week_id, pv_f2w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f2w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 7 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 13
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week3' as week_id, pv_f3w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f3w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 14 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 20
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week4' as week_id, pv_f4w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f4w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 21 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 27
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week5' as week_id, pv_f5w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f5w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 28 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 34
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week6' as week_id, pv_f6w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f6w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 35 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 41
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week7' as week_id, pv_f7w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f7w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 42 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 48
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT pv.warehouse, 'week8' as week_id, pv_f8w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f8w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 49 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 55
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week9' as week_id, pv_f9w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f9w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 56 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 62
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week10' as week_id, pv_f10w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f10w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 63 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 69
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week11' as week_id, pv_f11w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f11w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 70 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 76
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week12' as week_id, pv_f12w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f12w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 77 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 83
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week13' as week_id, pv_f13w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f13w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 84 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 90
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week14' as week_id, pv_f14w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f14w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 91 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 97
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week15' as week_id, pv_f15w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f15w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 98 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 104
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week16' as week_id, pv_f16w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f16w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 105 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 111
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week17' as week_id, pv_f17w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f17w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 112 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 118
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv

"""

In [32]:
df_id_web = wr.athena.read_sql_query(sql_id, database="web_production")

In [33]:
df_id_ios = wr.athena.read_sql_query(sql_id, database="ios_pomelo_fashion_production")

In [34]:
df_id_and = wr.athena.read_sql_query(
    sql_id, database="android_pomelo_fashion_production"
)

In [35]:
df_id_web.rename(columns={"lookbook_pv": "lookbook_pv_web"}, inplace=True)

In [36]:
df_id_ios.rename(columns={"lookbook_pv": "lookbook_pv_ios"}, inplace=True)

In [37]:
df_id_and.rename(columns={"lookbook_pv": "lookbook_pv_and"}, inplace=True)

In [38]:
df_id_list = [df_id_web, df_id_ios, df_id_and]

In [39]:
df_id = reduce(
    lambda left, right: pd.merge(left, right, on=["warehouse", "week_id"]), df_id_list
)

In [40]:
df_id

   warehouse week_id  lookbook_pv_web  lookbook_pv_ios  lookbook_pv_and
0         ID   week1             1177            34800            19453
1         ID   week3              234             9909             7479
2         ID   week4               95            10148             6521
3         ID  week14               12             1934              928
4         ID   week6               34             6008             3932
5         ID  week15               24             1588              970
6         ID   week5               61             6775             3824
7         ID  week10               62             3395             1916
8         ID  week12               18             1481              963
9         ID  week16               11             1848             1050
10        ID   week2              202            16378            11308
11        ID   week7               66             5141             2928
12        ID   week9               48             3717             2104
13        ID  week11               82             2411             1939
14        ID   week8               18             4429             2912
15        ID  week17               19             1580              731

In [41]:
df_id["lookbook_pv"] = (
    df_id["lookbook_pv_web"] + df_id["lookbook_pv_ios"] + df_id["lookbook_pv_and"]
)

In [42]:
df_id = df_id.sort_values("week_id")
df_id

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
0,ID,week1,1177,34800,19453,55430
7,ID,week10,62,3395,1916,5373
13,ID,week11,82,2411,1939,4432
8,ID,week12,18,1481,963,2462
3,ID,week14,12,1934,928,2874
5,ID,week15,24,1588,970,2582
9,ID,week16,11,1848,1050,2909
15,ID,week17,19,1580,731,2330
10,ID,week2,202,16378,11308,27888
1,ID,week3,234,9909,7479,17622
2,ID,week4,95,10148,6521,16764
6,ID,week5,61,6775,3824,10660
4,ID,week6,34,6008,3932,9974
11,ID,week7,66,5141,2928,8135
14,ID,week8,18,4429,2912,7359
12,ID,week9,48,3717,2104,5869

In [43]:
# line1 = pd.DataFrame({"warehouse": "ID", "week_id": "week8","lookbook_pv_web":0,"lookbook_pv_ios":0,"lookbook_pv_and":0,\
#                     "lookbook_pv":0},index=[7])
# df_id = df_id.append(line1, ignore_index=True)

# line2 = pd.DataFrame({"warehouse": "ID", "week_id": "week6","lookbook_pv_web":0,"lookbook_pv_ios":0,"lookbook_pv_and":0,\
#                     "lookbook_pv":0},index=[9])

In [44]:
# df_id = df_id.append(line2, ignore_index=True)

In [45]:
df_id

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
0,ID,week1,1177,34800,19453,55430
7,ID,week10,62,3395,1916,5373
13,ID,week11,82,2411,1939,4432
8,ID,week12,18,1481,963,2462
3,ID,week14,12,1934,928,2874
5,ID,week15,24,1588,970,2582
9,ID,week16,11,1848,1050,2909
15,ID,week17,19,1580,731,2330
10,ID,week2,202,16378,11308,27888
1,ID,week3,234,9909,7479,17622
2,ID,week4,95,10148,6521,16764
6,ID,week5,61,6775,3824,10660
4,ID,week6,34,6008,3932,9974
11,ID,week7,66,5141,2928,8135
14,ID,week8,18,4429,2912,7359
12,ID,week9,48,3717,2104,5869

# con cat all warehouse

In [46]:
df_all = pd.concat([df_th, df_my, df_id])

In [47]:
df_all = df_all[["warehouse", "week_id", "lookbook_pv"]]

In [48]:
df_all

   warehouse week_id  lookbook_pv
2         TH   week1       363090
5         TH  week10        20911
10        TH  week11        20409
11        TH  week12        22536
0         TH  week13        18065
13        TH  week14        21725
1         TH  week15        17174
4         TH  week16        12119
3         TH  week17        13366
12        TH   week2       219849
9         TH   week3       111589
14        TH   week4       106949
8         TH   week5        80653
16        TH   week6        54433
7         TH   week7        43853
6         TH   week8        30239
15        TH   week9        25306
9         MY   week1        81756
5         MY  week10         4492
8         MY  week11         2086
11        MY  week12         1328
3         MY  week13         1450
4         MY  week14          938
12        MY  week15         1744
6         MY  week16         1260
2         MY  week17          962
7         MY   week2        40776
0         MY   week3        23716
13        MY   week4        17387
10        MY   week5         8637
16        MY   week6         7923
15        MY   week7         7054
1         MY   week8         3570
14        MY   week9         2946
0         ID   week1        55430
7         ID  week10         5373
13        ID  week11         4432
8         ID  week12         2462
3         ID  week14         2874
5         ID  week15         2582
9         ID  week16         2909
15        ID  week17         2330
10        ID   week2        27888
1         ID   week3        17622
2         ID   week4        16764
6         ID   week5        10660
4         ID   week6         9974
11        ID   week7         8135
14        ID   week8         7359
12        ID   week9         5869

In [49]:
# find totoal pageview
pv_tot = (
    df_all.groupby("warehouse")["lookbook_pv"]
    .sum()
    .reset_index()
    .rename(columns={"lookbook_pv": "tot_lookbook_pv"})
)

In [50]:
pv_tot

  warehouse  tot_lookbook_pv
0        ID           182663
1        MY           208025
2        TH          1182266

In [51]:
df_pv_final = df_all.merge(pv_tot, on="warehouse")
df_pv_final

   warehouse week_id  lookbook_pv  tot_lookbook_pv
0         TH   week1       363090          1182266
1         TH  week10        20911          1182266
2         TH  week11        20409          1182266
3         TH  week12        22536          1182266
4         TH  week13        18065          1182266
5         TH  week14        21725          1182266
6         TH  week15        17174          1182266
7         TH  week16        12119          1182266
8         TH  week17        13366          1182266
9         TH   week2       219849          1182266
10        TH   week3       111589          1182266
11        TH   week4       106949          1182266
12        TH   week5        80653          1182266
13        TH   week6        54433          1182266
14        TH   week7        43853          1182266
15        TH   week8        30239          1182266
16        TH   week9        25306          1182266
17        MY   week1        81756           208025
18        MY  week10         4492           208025
19        MY  week11         2086           208025
20        MY  week12         1328           208025
21        MY  week13         1450           208025
22        MY  week14          938           208025
23        MY  week15         1744           208025
24        MY  week16         1260           208025
25        MY  week17          962           208025
26        MY   week2        40776           208025
27        MY   week3        23716           208025
28        MY   week4        17387           208025
29        MY   week5         8637           208025
30        MY   week6         7923           208025
31        MY   week7         7054           208025
32        MY   week8         3570           208025
33        MY   week9         2946           208025
34        ID   week1        55430           182663
35        ID  week10         5373           182663
36        ID  week11         4432           182663
37        ID  week12         2462           182663
38        ID  week14         2874           182663
39        ID  week15         2582           182663
40        ID  week16         2909           182663
41        ID  week17         2330           182663
42        ID   week2        27888           182663
43        ID   week3        17622           182663
44        ID   week4        16764           182663
45        ID   week5        10660           182663
46        ID   week6         9974           182663
47        ID   week7         8135           182663
48        ID   week8         7359           182663
49        ID   week9         5869           182663

In [52]:
df_pv_final["lookbook_pv_dist"] = (
    df_pv_final["lookbook_pv"] / df_pv_final["tot_lookbook_pv"]
)

In [53]:
df_pv_final.sort_values(["week_id", "warehouse"], inplace=True)

In [54]:
df_pv_final = df_pv_final.reset_index(drop=True)

In [55]:
df_pv_final

   warehouse week_id  lookbook_pv  tot_lookbook_pv  lookbook_pv_dist
0         ID   week1        55430           182663          0.303455
1         MY   week1        81756           208025          0.393010
2         TH   week1       363090          1182266          0.307114
3         ID  week10         5373           182663          0.029415
4         MY  week10         4492           208025          0.021594
5         TH  week10        20911          1182266          0.017687
6         ID  week11         4432           182663          0.024263
7         MY  week11         2086           208025          0.010028
8         TH  week11        20409          1182266          0.017263
9         ID  week12         2462           182663          0.013478
10        MY  week12         1328           208025          0.006384
11        TH  week12        22536          1182266          0.019062
12        MY  week13         1450           208025          0.006970
13        TH  week13        18065          1182266          0.015280
14        ID  week14         2874           182663          0.015734
15        MY  week14          938           208025          0.004509
16        TH  week14        21725          1182266          0.018376
17        ID  week15         2582           182663          0.014135
18        MY  week15         1744           208025          0.008384
19        TH  week15        17174          1182266          0.014526
20        ID  week16         2909           182663          0.015926
21        MY  week16         1260           208025          0.006057
22        TH  week16        12119          1182266          0.010251
23        ID  week17         2330           182663          0.012756
24        MY  week17          962           208025          0.004624
25        TH  week17        13366          1182266          0.011305
26        ID   week2        27888           182663          0.152675
27        MY   week2        40776           208025          0.196015
28        TH   week2       219849          1182266          0.185956
29        ID   week3        17622           182663          0.096473
30        MY   week3        23716           208025          0.114006
31        TH   week3       111589          1182266          0.094386
32        ID   week4        16764           182663          0.091776
33        MY   week4        17387           208025          0.083581
34        TH   week4       106949          1182266          0.090461
35        ID   week5        10660           182663          0.058359
36        MY   week5         8637           208025          0.041519
37        TH   week5        80653          1182266          0.068219
38        ID   week6         9974           182663          0.054603
39        MY   week6         7923           208025          0.038087
40        TH   week6        54433          1182266          0.046041
41        ID   week7         8135           182663          0.044536
42        MY   week7         7054           208025          0.033909
43        TH   week7        43853          1182266          0.037092
44        ID   week8         7359           182663          0.040287
45        MY   week8         3570           208025          0.017161
46        TH   week8        30239          1182266          0.025577
47        ID   week9         5869           182663          0.032130
48        MY   week9         2946           208025          0.014162
49        TH   week9        25306          1182266          0.021405

In [56]:
df_pv_final.to_csv(
    "s3://hal-bi-bucket/data_science/dfm/online_clothing_v2/data/deploy_loobook_pv_dist.csv",
    index=False,
)

In [57]:
dictionary = {
    "week10": "weeks10",
    "week11": "weeks11",
    "week12": "weeks12",
    "week13": "weeks13",
    "week14": "weeks14",
    "week15": "weeks15",
    "week16": "weeks16",
    "week17": "weeks17",
}
for key in dictionary.keys():
    df_pv_final["week_id"] = df_pv_final["week_id"].replace(key, dictionary[key])

df_pv_final = df_pv_final.sort_values(by="week_id")

In [58]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
    rows=3,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.02,
    subplot_titles=("TH", "MY", "ID"),
)

fig.add_trace(
    go.Scatter(
        x=df_pv_final[df_pv_final["warehouse"] == "ID"]["week_id"],
        y=df_pv_final[df_pv_final["warehouse"] == "ID"]["lookbook_pv_dist"],
    ),
    row=3,
    col=1,
)

fig.add_trace(
    go.Scatter(
        x=df_pv_final[df_pv_final["warehouse"] == "MY"]["week_id"],
        y=df_pv_final[df_pv_final["warehouse"] == "MY"]["lookbook_pv_dist"],
    ),
    row=2,
    col=1,
)

fig.add_trace(
    go.Scatter(
        x=df_pv_final[df_pv_final["warehouse"] == "TH"]["week_id"],
        y=df_pv_final[df_pv_final["warehouse"] == "TH"]["lookbook_pv_dist"],
    ),
    row=1,
    col=1,
)

fig.update_layout(height=900, width=900, title_text="lookbook_pv_dist by warehouse")
fig.update_xaxes(type="category")
fig.update_xaxes(categoryorder="category ascending")

fig.write_html(
    f"/home/ec2-user/SageMaker/business-intelligence-notebooks/dfm_clothing/online_dfm_v2/plot/plot_lookbook_pv_dist_deploy.html"
)