In [1]:
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import pandas as pd
import numpy as np
import random
from pomelo.utils import Hal

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)

In [2]:
end_date = date.today().strftime("%Y-%m-%d")
one_year = date.today() - relativedelta(months=+12)
start_date = one_year.strftime("%Y-%m-%d")

In [3]:
end_date

'2021-09-13'

In [4]:
start_date

'2020-09-13'

In [5]:
hal = Hal()

sql = f"""
SELECT fpp.id_product,
        CASE WHEN fpp.id_shop = 5 THEN 'ID' 
              WHEN fpp.id_shop = 2 THEN 'MY'
              WHEN fpp.id_shop = 11 THEN 'MY'
              WHEN fpp.id_shop = 14 THEN 'MY'
              ELSE 'TH' END as warehouse
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 0 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 6 THEN fpp.counter ELSE 0 END) as week1
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 7 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 13 THEN fpp.counter ELSE 0 END) as week2
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 14 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 20 THEN fpp.counter ELSE 0 END) as week3
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 21 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 27 THEN fpp.counter ELSE 0 END) as week4
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 28 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 34 THEN fpp.counter ELSE 0 END) as week5
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 35 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 41 THEN fpp.counter ELSE 0 END) as week6
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 42 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 48 THEN fpp.counter ELSE 0 END) as week7
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 49 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 55 THEN fpp.counter ELSE 0 END) as week8
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 56 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 62 THEN fpp.counter ELSE 0 END) as week9

,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 63 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 69 THEN fpp.counter ELSE 0 END) as week10
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 70 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 76 THEN fpp.counter ELSE 0 END) as week11
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 77 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 83 THEN fpp.counter ELSE 0 END) as week12
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 84 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 90 THEN fpp.counter ELSE 0 END) as week13
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 91 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 97 THEN fpp.counter ELSE 0 END) as week14
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 98 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 104 THEN fpp.counter ELSE 0 END) as week15
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 105 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 111 THEN fpp.counter ELSE 0 END) as week16
,SUM(CASE WHEN DATEDIFF(days,dp.date_released ,fpp.date_view) >= 112 AND DATEDIFF(days,dp.date_released ,fpp.date_view) <= 118 THEN fpp.counter ELSE 0 END) as week17
 
FROM dwh.fact_product_pageview fpp 
LEFT JOIN dwh.dim_product dp 
ON dp.id_product = fpp.id_product

WHERE dp.date_released BETWEEN '{start_date}' AND '{end_date}'
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
Group by 1,2

"""

Insert your Github token to access Vault:

GithubToken ········································

In [7]:
pv_dist = hal.get_pandas_df(sql)

In [8]:
pv_dist

,id_product,warehouse,week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17
0,30820,MY,1476,1098,426,228,300,408,492,336,1458,372,864,486,720,270,270,942,2886
1,31322,ID,4542,5334,12,594,636,816,1158,426,720,348,558,114,198,216,228,198,348
2,31520,MY,33870,2568,1110,1812,900,1068,198,168,456,1290,738,708,348,372,492,378,774
3,31984,TH,6552,8124,2640,1950,1902,1836,1824,3402,5142,2766,5148,2898,2610,1674,2226,9336,10524
4,32453,TH,62490,2898,4044,8658,20028,7026,1752,1398,666,408,624,786,72,6,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5836,46010,MY,7152,3600,1902,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5837,53188,TH,3888,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5838,46359,MY,2382,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5839,53189,MY,954,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5840,40097,ID,0,0,0,0,0,6,168,0,0,0,0,0,0,0,0,0,0

In [9]:
pv_dist = pv_dist.groupby("warehouse").sum().reset_index()
del pv_dist["id_product"]
pv_dist

,warehouse,week1,week2,week3,week4,week5,week6,week7,week8,week9,week10,week11,week12,week13,week14,week15,week16,week17
0,ID,5633014,2426102,2220872,2875737,2323917,2856422,2166245,2371605,2137626,1796828,1577065,1530998,1569697,1349423,1176751,1098377,1086386
1,MY,11606433,4392754,4036741,3289865,2313298,2465948,2126422,2471448,2069098,1818928,1733729,1672346,1601803,1565609,1327787,1540409,1482580
2,TH,36616044,12912836,10860060,8572078,7342862,7066303,6132595,5607513,5427149,5235168,4935439,4657183,3709316,4258341,3199655,3622041,3821635

In [10]:
pv_dist2 = pv_dist.iloc[:, :]

In [11]:
pv_dist_unpivot = pv_dist2.melt(
    id_vars=["warehouse"], var_name="week_id", value_name="pv"
)
pv_dist_unpivot

   warehouse week_id        pv
0         ID   week1   5633014
1         MY   week1  11606433
2         TH   week1  36616044
3         ID   week2   2426102
4         MY   week2   4392754
5         TH   week2  12912836
6         ID   week3   2220872
7         MY   week3   4036741
8         TH   week3  10860060
9         ID   week4   2875737
10        MY   week4   3289865
11        TH   week4   8572078
12        ID   week5   2323917
13        MY   week5   2313298
14        TH   week5   7342862
15        ID   week6   2856422
16        MY   week6   2465948
17        TH   week6   7066303
18        ID   week7   2166245
19        MY   week7   2126422
20        TH   week7   6132595
21        ID   week8   2371605
22        MY   week8   2471448
23        TH   week8   5607513
24        ID   week9   2137626
25        MY   week9   2069098
26        TH   week9   5427149
27        ID  week10   1796828
28        MY  week10   1818928
29        TH  week10   5235168
30        ID  week11   1577065
31        MY  week11   1733729
32        TH  week11   4935439
33        ID  week12   1530998
34        MY  week12   1672346
35        TH  week12   4657183
36        ID  week13   1569697
37        MY  week13   1601803
38        TH  week13   3709316
39        ID  week14   1349423
40        MY  week14   1565609
41        TH  week14   4258341
42        ID  week15   1176751
43        MY  week15   1327787
44        TH  week15   3199655
45        ID  week16   1098377
46        MY  week16   1540409
47        TH  week16   3622041
48        ID  week17   1086386
49        MY  week17   1482580
50        TH  week17   3821635

In [12]:
# find totoal pageview
pv_tot = (
    pv_dist_unpivot.groupby("warehouse")["pv"]
    .sum()
    .reset_index()
    .rename(columns={"pv": "tot_pv"})
)

In [13]:
df = pv_dist_unpivot.merge(pv_tot[["warehouse", "tot_pv"]], on="warehouse")
df

   warehouse week_id        pv     tot_pv
0         ID   week1   5633014   36197065
1         ID   week2   2426102   36197065
2         ID   week3   2220872   36197065
3         ID   week4   2875737   36197065
4         ID   week5   2323917   36197065
5         ID   week6   2856422   36197065
6         ID   week7   2166245   36197065
7         ID   week8   2371605   36197065
8         ID   week9   2137626   36197065
9         ID  week10   1796828   36197065
10        ID  week11   1577065   36197065
11        ID  week12   1530998   36197065
12        ID  week13   1569697   36197065
13        ID  week14   1349423   36197065
14        ID  week15   1176751   36197065
15        ID  week16   1098377   36197065
16        ID  week17   1086386   36197065
17        MY   week1  11606433   47515198
18        MY   week2   4392754   47515198
19        MY   week3   4036741   47515198
20        MY   week4   3289865   47515198
21        MY   week5   2313298   47515198
22        MY   week6   2465948   47515198
23        MY   week7   2126422   47515198
24        MY   week8   2471448   47515198
25        MY   week9   2069098   47515198
26        MY  week10   1818928   47515198
27        MY  week11   1733729   47515198
28        MY  week12   1672346   47515198
29        MY  week13   1601803   47515198
30        MY  week14   1565609   47515198
31        MY  week15   1327787   47515198
32        MY  week16   1540409   47515198
33        MY  week17   1482580   47515198
34        TH   week1  36616044  133976218
35        TH   week2  12912836  133976218
36        TH   week3  10860060  133976218
37        TH   week4   8572078  133976218
38        TH   week5   7342862  133976218
39        TH   week6   7066303  133976218
40        TH   week7   6132595  133976218
41        TH   week8   5607513  133976218
42        TH   week9   5427149  133976218
43        TH  week10   5235168  133976218
44        TH  week11   4935439  133976218
45        TH  week12   4657183  133976218
46        TH  week13   3709316  133976218
47        TH  week14   4258341  133976218
48        TH  week15   3199655  133976218
49        TH  week16   3622041  133976218
50        TH  week17   3821635  133976218

In [14]:
df["pv_dist"] = df["pv"] / df["tot_pv"]

In [15]:
df

   warehouse week_id        pv     tot_pv   pv_dist
0         ID   week1   5633014   36197065  0.155621
1         ID   week2   2426102   36197065  0.067025
2         ID   week3   2220872   36197065  0.061355
3         ID   week4   2875737   36197065  0.079447
4         ID   week5   2323917   36197065  0.064202
5         ID   week6   2856422   36197065  0.078913
6         ID   week7   2166245   36197065  0.059846
7         ID   week8   2371605   36197065  0.065519
8         ID   week9   2137626   36197065  0.059055
9         ID  week10   1796828   36197065  0.049640
10        ID  week11   1577065   36197065  0.043569
11        ID  week12   1530998   36197065  0.042296
12        ID  week13   1569697   36197065  0.043365
13        ID  week14   1349423   36197065  0.037280
14        ID  week15   1176751   36197065  0.032510
15        ID  week16   1098377   36197065  0.030344
16        ID  week17   1086386   36197065  0.030013
17        MY   week1  11606433   47515198  0.244268
18        MY   week2   4392754   47515198  0.092449
19        MY   week3   4036741   47515198  0.084957
20        MY   week4   3289865   47515198  0.069238
21        MY   week5   2313298   47515198  0.048685
22        MY   week6   2465948   47515198  0.051898
23        MY   week7   2126422   47515198  0.044752
24        MY   week8   2471448   47515198  0.052014
25        MY   week9   2069098   47515198  0.043546
26        MY  week10   1818928   47515198  0.038281
27        MY  week11   1733729   47515198  0.036488
28        MY  week12   1672346   47515198  0.035196
29        MY  week13   1601803   47515198  0.033711
30        MY  week14   1565609   47515198  0.032950
31        MY  week15   1327787   47515198  0.027944
32        MY  week16   1540409   47515198  0.032419
33        MY  week17   1482580   47515198  0.031202
34        TH   week1  36616044  133976218  0.273303
35        TH   week2  12912836  133976218  0.096382
36        TH   week3  10860060  133976218  0.081060
37        TH   week4   8572078  133976218  0.063982
38        TH   week5   7342862  133976218  0.054807
39        TH   week6   7066303  133976218  0.052743
40        TH   week7   6132595  133976218  0.045774
41        TH   week8   5607513  133976218  0.041855
42        TH   week9   5427149  133976218  0.040508
43        TH  week10   5235168  133976218  0.039075
44        TH  week11   4935439  133976218  0.036838
45        TH  week12   4657183  133976218  0.034761
46        TH  week13   3709316  133976218  0.027686
47        TH  week14   4258341  133976218  0.031784
48        TH  week15   3199655  133976218  0.023882
49        TH  week16   3622041  133976218  0.027035
50        TH  week17   3821635  133976218  0.028525

In [16]:
df.to_csv(
    "s3://hal-bi-bucket/data_science/dfm/online_clothing_v2/data/pv_dist_train.csv",
    index=False,
)

In [15]:
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(
    rows=3,
    cols=1,
    shared_xaxes=True,
    vertical_spacing=0.02,
    subplot_titles=("TH", "MY", "ID"),
)

fig.add_trace(
    go.Scatter(
        x=df[df["warehouse"] == "ID"]["week_id"],
        y=df[df["warehouse"] == "ID"]["pv_dist"],
    ),
    row=3,
    col=1,
)

fig.add_trace(
    go.Scatter(
        x=df[df["warehouse"] == "MY"]["week_id"],
        y=df[df["warehouse"] == "MY"]["pv_dist"],
    ),
    row=2,
    col=1,
)

fig.add_trace(
    go.Scatter(
        x=df[df["warehouse"] == "TH"]["week_id"],
        y=df[df["warehouse"] == "TH"]["pv_dist"],
    ),
    row=1,
    col=1,
)

fig.update_layout(height=900, width=900, title_text="pv dist by warehouse")

fig.write_html(
    f"/home/ec2-user/SageMaker/business-intelligence-notebooks/dfm_clothing/online_dfm_v2/plot_pv_dist_train.html"
)