In [70]:
!pip install pyarrow==2 awswrangler

Requirement already satisfied: pyarrow==2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.0.0)
Requirement already satisfied: awswrangler in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (2.11.0)
Requirement already satisfied: numpy>=1.14 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pyarrow==2) (1.18.5)
Requirement already satisfied: redshift-connector<2.1.0,>=2.0.884 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.886)
Requirement already satisfied: botocore<2.0.0,>=1.19.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.21.28)
Requirement already satisfied: xlwt<2.0.0,>=1.3.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.3.0)
Requirement already satisfied: boto3<2.0.0,>=1.16.8 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.18.28)
Requirement already satisfied: pandas<1.2.0,>=1.1.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.1.5)
Requirement already satisfied: pg8000<1.22.0,>=1.16.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (1.21.1)
Requirement already satisfied: openpyxl<3.1.0,>=3.0.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (3.0.6)
Requirement already satisfied: pymysql<1.1.0,>=0.9.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (0.9.3)
Requirement already satisfied: xlrd<3.0.0,>=2.0.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from awswrangler) (2.0.1)
Requirement already satisfied: s3transfer<0.6.0,>=0.5.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.0.0,>=1.16.8->awswrangler) (0.5.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from boto3<2.0.0,>=1.16.8->awswrangler) (0.10.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.0.0,>=1.19.8->awswrangler) (2.8.1)
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from botocore<2.0.0,>=1.19.8->awswrangler) (1.26.6)
Requirement already satisfied: jdcal in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.4.1)
Requirement already satisfied: et-xmlfile in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from openpyxl<3.1.0,>=3.0.0->awswrangler) (1.0.1)
Requirement already satisfied: pytz>=2017.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pandas<1.2.0,>=1.1.0->awswrangler) (2021.1)
Requirement already satisfied: scramp>=1.4.1 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from pg8000<1.22.0,>=1.16.0->awswrangler) (1.4.1)
Requirement already satisfied: six>=1.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<2.0.0,>=1.19.8->awswrangler) (1.15.0)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.7.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (4.9.3)
Requirement already satisfied: packaging in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (20.9)
Requirement already satisfied: requests<2.25.2,>=2.23.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.25.1)
Requirement already satisfied: lxml>=4.6.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from redshift-connector<2.1.0,>=2.0.884->awswrangler) (4.6.3)
Requirement already satisfied: soupsieve>1.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from beautifulsoup4<5.0.0,>=4.7.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.25.2,>=2.23.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2021.5.30)
Requirement already satisfied: chardet<5,>=3.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.25.2,>=2.23.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from requests<2.25.2,>=2.23.0->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.10)
Requirement already satisfied: asn1crypto>=1.4.0 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from scramp>=1.4.1->pg8000<1.22.0,>=1.16.0->awswrangler) (1.4.0)
Requirement already satisfied: pyparsing>=2.0.2 in /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages (from packaging->redshift-connector<2.1.0,>=2.0.884->awswrangler) (2.4.7)
WARNING: You are using pip version 21.1.3; however, version 21.2.4 is available.
You should consider upgrading via the '/home/ec2-user/anaconda3/envs/python3/bin/python -m pip install --upgrade pip' command.

In [71]:
import awswrangler as wr
import pandas as pd
from datetime import datetime, timedelta, date
from dateutil.relativedelta import relativedelta
import numpy as np

In [72]:
end_date = date.today().strftime("%Y-%m-%d")
tw_months = date.today() - relativedelta(months=+12)
start_date = tw_months.strftime("%Y-%m-%d")

In [73]:
start_date

'2020-09-13'

In [74]:
end_date

'2021-09-13'

In [75]:
sql_th = f"""
SELECT  pv.warehouse, 'week1' as week_id, pv_f1w as lookbook_pv
from
(select
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f1w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 0 AND date_diff('day',dp.date_released ,pv.sent_at) <= 6
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1
) pv
Union all
SELECT  pv.warehouse, 'week2' as week_id, pv_f2w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f2w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 7 AND date_diff('day',dp.date_released ,pv.sent_at) <= 13
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week3' as week_id, pv_f3w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f3w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 14 AND date_diff('day',dp.date_released ,pv.sent_at) <= 20
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week4' as week_id, pv_f4w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f4w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 21 AND date_diff('day',dp.date_released ,pv.sent_at) <= 27
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week5' as week_id, pv_f5w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f5w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 28 AND date_diff('day',dp.date_released ,pv.sent_at) <= 34
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week6' as week_id, pv_f6w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f6w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 35 AND date_diff('day',dp.date_released ,pv.sent_at) <= 41
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week7' as week_id, pv_f7w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f7w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 42 AND date_diff('day',dp.date_released ,pv.sent_at) <= 48
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT pv.warehouse, 'week8' as week_id, pv_f8w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f8w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 49 AND date_diff('day',dp.date_released ,pv.sent_at) <= 55
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week9' as week_id, pv_f9w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f9w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 56 AND date_diff('day',dp.date_released ,pv.sent_at) <= 62
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week10' as week_id, pv_f10w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f10w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 63 AND date_diff('day',dp.date_released ,pv.sent_at) <= 69
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week11' as week_id, pv_f11w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f11w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 70 AND date_diff('day',dp.date_released ,pv.sent_at) <= 76
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week12' as week_id, pv_f12w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f12w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 77 AND date_diff('day',dp.date_released ,pv.sent_at) <= 83
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week13' as week_id, pv_f13w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f13w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 84 AND date_diff('day',dp.date_released ,pv.sent_at) <= 90
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week14' as week_id, pv_f14w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f14w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 91 AND date_diff('day',dp.date_released ,pv.sent_at) <= 97
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week15' as week_id, pv_f15w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f15w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 98 AND date_diff('day',dp.date_released ,pv.sent_at) <= 104
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week16' as week_id, pv_f16w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f16w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 105 AND date_diff('day',dp.date_released ,pv.sent_at) <= 111
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week17' as week_id, pv_f17w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f17w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop NOT IN (2,11,5)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 112 AND date_diff('day',dp.date_released ,pv.sent_at) <= 118
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
"""

In [76]:
# Retrieving the data from Amazon Athena
df_th_web = wr.athena.read_sql_query(sql_th, database="web_production")

In [77]:
# Retrieving the data from Amazon Athena
df_th_ios = wr.athena.read_sql_query(sql_th, database="ios_pomelo_fashion_production")

In [78]:
df_th_and = wr.athena.read_sql_query(
    sql_th, database="android_pomelo_fashion_production"
)

In [79]:
df_th_web.rename(columns={"lookbook_pv": "lookbook_pv_web"}, inplace=True)

In [80]:
df_th_ios.rename(columns={"lookbook_pv": "lookbook_pv_ios"}, inplace=True)

In [81]:
df_th_and.rename(columns={"lookbook_pv": "lookbook_pv_and"}, inplace=True)

In [82]:
df_th_list = [df_th_web, df_th_ios, df_th_and]

In [83]:
from functools import reduce

In [84]:
df_th = reduce(
    lambda left, right: pd.merge(left, right, on=["warehouse", "week_id"]), df_th_list
)

In [85]:
df_th

   warehouse week_id  lookbook_pv_web  lookbook_pv_ios  lookbook_pv_and
0         TH   week2             6332           154761            49656
1         TH  week16              385            11927             2408
2         TH  week11              957            27022             7205
3         TH   week3             4737            67399            20724
4         TH  week15              469            16528             4566
5         TH   week1            21815           505344           138954
6         TH   week8             1619            68455            22999
7         TH   week5             2049            45678            12111
8         TH  week13              633            20211             4704
9         TH   week7             1368            53078            17325
10        TH   week4             3542            78815            24290
11        TH  week12              858            25226             5811
12        TH  week14              437            17101             4763
13        TH   week9             1285            41040            12710
14        TH  week10             1337            26811             6926
15        TH   week6             1652            26402             8688
16        TH  week17              453            13339             2593

In [86]:
df_th["lookbook_pv"] = (
    df_th["lookbook_pv_web"] + df_th["lookbook_pv_ios"] + df_th["lookbook_pv_and"]
)

In [87]:
df_th = df_th.sort_values("week_id")
df_th

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
5,TH,week1,21815,505344,138954,666113
14,TH,week10,1337,26811,6926,35074
2,TH,week11,957,27022,7205,35184
11,TH,week12,858,25226,5811,31895
8,TH,week13,633,20211,4704,25548
12,TH,week14,437,17101,4763,22301
4,TH,week15,469,16528,4566,21563
1,TH,week16,385,11927,2408,14720
16,TH,week17,453,13339,2593,16385
0,TH,week2,6332,154761,49656,210749
3,TH,week3,4737,67399,20724,92860
10,TH,week4,3542,78815,24290,106647
7,TH,week5,2049,45678,12111,59838
15,TH,week6,1652,26402,8688,36742
9,TH,week7,1368,53078,17325,71771
6,TH,week8,1619,68455,22999,93073
13,TH,week9,1285,41040,12710,55035

# MY

In [88]:
sql_my = f"""
SELECT  pv.warehouse, 'week1' as week_id, pv_f1w as lookbook_pv
from
(select
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f1w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 0 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 6
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1
) pv
Union all
SELECT  pv.warehouse, 'week2' as week_id, pv_f2w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f2w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 7 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 13
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week3' as week_id, pv_f3w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f3w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 14 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 20
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week4' as week_id, pv_f4w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f4w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 21 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 27
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week5' as week_id, pv_f5w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f5w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 28 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 34
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week6' as week_id, pv_f6w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f6w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 35 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 41
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week7' as week_id, pv_f7w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f7w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 42 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 48
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT pv.warehouse, 'week8' as week_id, pv_f8w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f8w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 49 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 55
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week9' as week_id, pv_f9w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f9w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_my BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released_my ,pv.sent_at) >= 56 AND date_diff('day',dp.date_released_my ,pv.sent_at) <= 62
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week10' as week_id, pv_f10w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f10w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 63 AND date_diff('day',dp.date_released ,pv.sent_at) <= 69
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week11' as week_id, pv_f11w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f11w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 70 AND date_diff('day',dp.date_released ,pv.sent_at) <= 76
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week12' as week_id, pv_f12w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f12w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 77 AND date_diff('day',dp.date_released ,pv.sent_at) <= 83
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week13' as week_id, pv_f13w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f13w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 84 AND date_diff('day',dp.date_released ,pv.sent_at) <= 90
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week14' as week_id, pv_f14w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f14w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 91 AND date_diff('day',dp.date_released ,pv.sent_at) <= 97
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week15' as week_id, pv_f15w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f15w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 98 AND date_diff('day',dp.date_released ,pv.sent_at) <= 104
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week16' as week_id, pv_f16w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f16w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 105 AND date_diff('day',dp.date_released ,pv.sent_at) <= 111
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week17' as week_id, pv_f17w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f17w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop IN (2,11)
AND date_diff('day',dp.date_released ,pv.sent_at) >= 112 AND date_diff('day',dp.date_released ,pv.sent_at) <= 118
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv

"""

In [89]:
df_my_web = wr.athena.read_sql_query(sql_my, database="web_production")

In [90]:
df_my_ios = wr.athena.read_sql_query(sql_my, database="ios_pomelo_fashion_production")

In [91]:
df_my_and = wr.athena.read_sql_query(
    sql_my, database="android_pomelo_fashion_production"
)

In [92]:
df_my_web.rename(columns={"lookbook_pv": "lookbook_pv_web"}, inplace=True)

In [93]:
df_my_ios.rename(columns={"lookbook_pv": "lookbook_pv_ios"}, inplace=True)

In [94]:
df_my_and.rename(columns={"lookbook_pv": "lookbook_pv_and"}, inplace=True)

In [95]:
df_my_list = [df_my_web, df_my_ios, df_my_and]

In [96]:
df_my = reduce(
    lambda left, right: pd.merge(left, right, on=["warehouse", "week_id"]), df_my_list
)

In [97]:
df_my

   warehouse week_id  lookbook_pv_web  lookbook_pv_ios  lookbook_pv_and
0         MY   week1            10945           121878            54551
1         MY   week2             2157            36491            21133
2         MY   week3             1213            17637            10864
3         MY  week15              107             3890             1483
4         MY   week8              366            14559             6753
5         MY   week5              611             6528             4471
6         MY  week12              180             5219             2318
7         MY   week4             1132            17840             9395
8         MY   week9              301             9320             4208
9         MY  week13              211             4185             1864
10        MY  week10              321             6736             2229
11        MY  week16              195             3271             1117
12        MY  week17              277             2360              997
13        MY   week6              558             4256             3515
14        MY  week14              124             3191             1384
15        MY   week7              341            10440             5581
16        MY  week11              169             6367             2142

In [98]:
df_my["lookbook_pv"] = (
    df_my["lookbook_pv_web"] + df_my["lookbook_pv_ios"] + df_my["lookbook_pv_and"]
)

In [99]:
df_my = df_my.sort_values("week_id")
df_my

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
0,MY,week1,10945,121878,54551,187374
10,MY,week10,321,6736,2229,9286
16,MY,week11,169,6367,2142,8678
6,MY,week12,180,5219,2318,7717
9,MY,week13,211,4185,1864,6260
14,MY,week14,124,3191,1384,4699
3,MY,week15,107,3890,1483,5480
11,MY,week16,195,3271,1117,4583
12,MY,week17,277,2360,997,3634
1,MY,week2,2157,36491,21133,59781
2,MY,week3,1213,17637,10864,29714
7,MY,week4,1132,17840,9395,28367
5,MY,week5,611,6528,4471,11610
13,MY,week6,558,4256,3515,8329
15,MY,week7,341,10440,5581,16362
4,MY,week8,366,14559,6753,21678
8,MY,week9,301,9320,4208,13829

# ID

In [100]:
sql_id = f"""
SELECT  pv.warehouse, 'week1' as week_id, pv_f1w as lookbook_pv
from
(select
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f1w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 0 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 6
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1
) pv
Union all
SELECT  pv.warehouse, 'week2' as week_id, pv_f2w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f2w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 7 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 13
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week3' as week_id, pv_f3w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f3w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 14 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 20
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week4' as week_id, pv_f4w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f4w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 21 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 27
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week5' as week_id, pv_f5w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f5w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 28 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 34
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week6' as week_id, pv_f6w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f6w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 35 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 41
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week7' as week_id, pv_f7w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f7w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 42 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 48
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT pv.warehouse, 'week8' as week_id, pv_f8w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f8w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 49 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 55
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week9' as week_id, pv_f9w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f9w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released_id BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released_id ,pv.sent_at) >= 56 AND date_diff('day',dp.date_released_id ,pv.sent_at) <= 62
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week10' as week_id, pv_f10w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f10w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 63 AND date_diff('day',dp.date_released ,pv.sent_at) <= 69
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week11' as week_id, pv_f11w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f11w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 70 AND date_diff('day',dp.date_released ,pv.sent_at) <= 76
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week12' as week_id, pv_f12w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f12w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 77 AND date_diff('day',dp.date_released ,pv.sent_at) <= 83
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week13' as week_id, pv_f13w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f13w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 84 AND date_diff('day',dp.date_released ,pv.sent_at) <= 90
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week14' as week_id, pv_f14w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f14w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 91 AND date_diff('day',dp.date_released ,pv.sent_at) <= 97
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week15' as week_id, pv_f15w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f15w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 98 AND date_diff('day',dp.date_released ,pv.sent_at) <= 104
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week16' as week_id, pv_f16w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f16w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 105 AND date_diff('day',dp.date_released ,pv.sent_at) <= 111
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv
Union all
SELECT  pv.warehouse, 'week17' as week_id, pv_f17w as lookbook_pv
from
(select 
            CASE WHEN pv.id_shop = 5 THEN 'ID' 
              WHEN pv.id_shop = 2 THEN 'MY'
              WHEN pv.id_shop = 11 THEN 'MY'
              ELSE 'TH' END as warehouse
        ,count(pv.id_product)  as pv_f17w
FROM  product_viewed pv
join dwh.dim_product dp
on dp.id_product = pv.id_product
WHERE ref_type IN ('lookbook_shop_look','lookbook_shop')
AND dp.date_released BETWEEN TIMESTAMP '{start_date}' AND TIMESTAMP '{end_date}'
AND pv.id_shop = 5
AND date_diff('day',dp.date_released ,pv.sent_at) >= 112 AND date_diff('day',dp.date_released ,pv.sent_at) <= 118
AND dp.parent_product_line NOT IN ('Free Gift')
AND dp.product_line NOT IN('Bags','3P Apparel','Shoes')
AND dp.henry_category_1 NOT IN ('Accessories','Bags','Bath&Body','Beverage Container','Cosmetics','Hair','Miscellaneous','Shoes','Skin Care','Stationery')
AND dp.product_cost_usd_first_order_date > 0 
AND dp.brand IN ('Alita','Basics','Pomelo', 'BEET by Pomelo', 'Holiday Collection', 'Pomelo x Tex Saverio','Blackdog BKK')
AND dp.release_collection_name IS NOT NULL
group by 1) pv

"""

In [101]:
df_id_web = wr.athena.read_sql_query(sql_id, database="web_production")

In [102]:
df_id_ios = wr.athena.read_sql_query(sql_id, database="ios_pomelo_fashion_production")

In [103]:
df_id_and = wr.athena.read_sql_query(
    sql_id, database="android_pomelo_fashion_production"
)

In [104]:
df_id_web.rename(columns={"lookbook_pv": "lookbook_pv_web"}, inplace=True)

In [105]:
df_id_ios.rename(columns={"lookbook_pv": "lookbook_pv_ios"}, inplace=True)

In [106]:
df_id_and.rename(columns={"lookbook_pv": "lookbook_pv_and"}, inplace=True)

In [107]:
df_id_list = [df_id_web, df_id_ios, df_id_and]

In [108]:
df_id = reduce(
    lambda left, right: pd.merge(left, right, on=["warehouse", "week_id"]), df_id_list
)

In [109]:
df_id

   warehouse week_id  lookbook_pv_web  lookbook_pv_ios  lookbook_pv_and
0         ID   week8              381            20982            15346
1         ID  week14              116             2760             1609
2         ID   week4              858            12066             9193
3         ID  week10              127             5229             3043
4         ID   week6              299             5243             4912
5         ID  week16               37             3100              952
6         ID   week1             8159            75491            42602
7         ID   week3              958            14883            11125
8         ID   week5              406             6373             5514
9         ID   week7              416            12238             8468
10        ID  week12              107             5927             3107
11        ID   week9              144             6929             6521
12        ID   week2             1855            26127            17623
13        ID  week15               53             4288             2470
14        ID  week11              172             6276             3342
15        ID  week17               66             2325              856
16        ID  week13               63             3956             2220

In [110]:
df_id["lookbook_pv"] = (
    df_id["lookbook_pv_web"] + df_id["lookbook_pv_ios"] + df_id["lookbook_pv_and"]
)

In [111]:
df_id = df_id.sort_values("week_id")
df_id

,warehouse,week_id,lookbook_pv_web,lookbook_pv_ios,lookbook_pv_and,lookbook_pv
6,ID,week1,8159,75491,42602,126252
3,ID,week10,127,5229,3043,8399
14,ID,week11,172,6276,3342,9790
10,ID,week12,107,5927,3107,9141
16,ID,week13,63,3956,2220,6239
1,ID,week14,116,2760,1609,4485
13,ID,week15,53,4288,2470,6811
5,ID,week16,37,3100,952,4089
15,ID,week17,66,2325,856,3247
12,ID,week2,1855,26127,17623,45605
7,ID,week3,958,14883,11125,26966
2,ID,week4,858,12066,9193,22117
8,ID,week5,406,6373,5514,12293
4,ID,week6,299,5243,4912,10454
9,ID,week7,416,12238,8468,21122
0,ID,week8,381,20982,15346,36709
11,ID,week9,144,6929,6521,13594

# con cat all warehouse

In [112]:
df_all = pd.concat([df_th, df_my, df_id])

In [113]:
df_all = df_all[["warehouse", "week_id", "lookbook_pv"]]

In [114]:
df_all

   warehouse week_id  lookbook_pv
5         TH   week1       666113
14        TH  week10        35074
2         TH  week11        35184
11        TH  week12        31895
8         TH  week13        25548
12        TH  week14        22301
4         TH  week15        21563
1         TH  week16        14720
16        TH  week17        16385
0         TH   week2       210749
3         TH   week3        92860
10        TH   week4       106647
7         TH   week5        59838
15        TH   week6        36742
9         TH   week7        71771
6         TH   week8        93073
13        TH   week9        55035
0         MY   week1       187374
10        MY  week10         9286
16        MY  week11         8678
6         MY  week12         7717
9         MY  week13         6260
14        MY  week14         4699
3         MY  week15         5480
11        MY  week16         4583
12        MY  week17         3634
1         MY   week2        59781
2         MY   week3        29714
7         MY   week4        28367
5         MY   week5        11610
13        MY   week6         8329
15        MY   week7        16362
4         MY   week8        21678
8         MY   week9        13829
6         ID   week1       126252
3         ID  week10         8399
14        ID  week11         9790
10        ID  week12         9141
16        ID  week13         6239
1         ID  week14         4485
13        ID  week15         6811
5         ID  week16         4089
15        ID  week17         3247
12        ID   week2        45605
7         ID   week3        26966
2         ID   week4        22117
8         ID   week5        12293
4         ID   week6        10454
9         ID   week7        21122
0         ID   week8        36709
11        ID   week9        13594

In [115]:
# find totoal pageview
pv_tot = (
    df_all.groupby("warehouse")["lookbook_pv"]
    .sum()
    .reset_index()
    .rename(columns={"lookbook_pv": "tot_lookbook_pv"})
)

In [116]:
pv_tot

  warehouse  tot_lookbook_pv
0        ID           367313
1        MY           427381
2        TH          1595498

In [117]:
df_pv_final = df_all.merge(pv_tot, on="warehouse")
df_pv_final

   warehouse week_id  lookbook_pv  tot_lookbook_pv
0         TH   week1       666113          1595498
1         TH  week10        35074          1595498
2         TH  week11        35184          1595498
3         TH  week12        31895          1595498
4         TH  week13        25548          1595498
5         TH  week14        22301          1595498
6         TH  week15        21563          1595498
7         TH  week16        14720          1595498
8         TH  week17        16385          1595498
9         TH   week2       210749          1595498
10        TH   week3        92860          1595498
11        TH   week4       106647          1595498
12        TH   week5        59838          1595498
13        TH   week6        36742          1595498
14        TH   week7        71771          1595498
15        TH   week8        93073          1595498
16        TH   week9        55035          1595498
17        MY   week1       187374           427381
18        MY  week10         9286           427381
19        MY  week11         8678           427381
20        MY  week12         7717           427381
21        MY  week13         6260           427381
22        MY  week14         4699           427381
23        MY  week15         5480           427381
24        MY  week16         4583           427381
25        MY  week17         3634           427381
26        MY   week2        59781           427381
27        MY   week3        29714           427381
28        MY   week4        28367           427381
29        MY   week5        11610           427381
30        MY   week6         8329           427381
31        MY   week7        16362           427381
32        MY   week8        21678           427381
33        MY   week9        13829           427381
34        ID   week1       126252           367313
35        ID  week10         8399           367313
36        ID  week11         9790           367313
37        ID  week12         9141           367313
38        ID  week13         6239           367313
39        ID  week14         4485           367313
40        ID  week15         6811           367313
41        ID  week16         4089           367313
42        ID  week17         3247           367313
43        ID   week2        45605           367313
44        ID   week3        26966           367313
45        ID   week4        22117           367313
46        ID   week5        12293           367313
47        ID   week6        10454           367313
48        ID   week7        21122           367313
49        ID   week8        36709           367313
50        ID   week9        13594           367313

In [118]:
df_pv_final["lookbook_pv_dist"] = (
    df_pv_final["lookbook_pv"] / df_pv_final["tot_lookbook_pv"]
)

In [119]:
df_pv_final.sort_values(["week_id", "warehouse"], inplace=True)

In [120]:
df_pv_final = df_pv_final.reset_index(drop=True)

In [121]:
df_pv_final

   warehouse week_id  lookbook_pv  tot_lookbook_pv  lookbook_pv_dist
0         ID   week1       126252           367313          0.343718
1         MY   week1       187374           427381          0.438424
2         TH   week1       666113          1595498          0.417495
3         ID  week10         8399           367313          0.022866
4         MY  week10         9286           427381          0.021728
5         TH  week10        35074          1595498          0.021983
6         ID  week11         9790           367313          0.026653
7         MY  week11         8678           427381          0.020305
8         TH  week11        35184          1595498          0.022052
9         ID  week12         9141           367313          0.024886
10        MY  week12         7717           427381          0.018056
11        TH  week12        31895          1595498          0.019991
12        ID  week13         6239           367313          0.016986
13        MY  week13         6260           427381          0.014647
14        TH  week13        25548          1595498          0.016013
15        ID  week14         4485           367313          0.012210
16        MY  week14         4699           427381          0.010995
17        TH  week14        22301          1595498          0.013977
18        ID  week15         6811           367313          0.018543
19        MY  week15         5480           427381          0.012822
20        TH  week15        21563          1595498          0.013515
21        ID  week16         4089           367313          0.011132
22        MY  week16         4583           427381          0.010723
23        TH  week16        14720          1595498          0.009226
24        ID  week17         3247           367313          0.008840
25        MY  week17         3634           427381          0.008503
26        TH  week17        16385          1595498          0.010270
27        ID   week2        45605           367313          0.124158
28        MY   week2        59781           427381          0.139878
29        TH   week2       210749          1595498          0.132090
30        ID   week3        26966           367313          0.073414
31        MY   week3        29714           427381          0.069526
32        TH   week3        92860          1595498          0.058201
33        ID   week4        22117           367313          0.060213
34        MY   week4        28367           427381          0.066374
35        TH   week4       106647          1595498          0.066842
36        ID   week5        12293           367313          0.033467
37        MY   week5        11610           427381          0.027165
38        TH   week5        59838          1595498          0.037504
39        ID   week6        10454           367313          0.028461
40        MY   week6         8329           427381          0.019488
41        TH   week6        36742          1595498          0.023029
42        ID   week7        21122           367313          0.057504
43        MY   week7        16362           427381          0.038284
44        TH   week7        71771          1595498          0.044983
45        ID   week8        36709           367313          0.099939
46        MY   week8        21678           427381          0.050723
47        TH   week8        93073          1595498          0.058335
48        ID   week9        13594           367313          0.037009
49        MY   week9        13829           427381          0.032358
50        TH   week9        55035          1595498          0.034494

In [122]:
df_pv_final.to_csv(
    "s3://hal-bi-bucket/data_science/dfm/online_clothing_v2/data/train_loobook_pv_dist.csv",
    index=False,
)